ecom/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"

urlpatterns = [

    path('add_cart/<slug:p>',views.add_cart,name="add_cart"),
    path('cartview',views.cartview,name="cartview"),


]

ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/', include('cart.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)

ecom/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search',views.searchresult,name='searchresult'),


]

ecom/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    # path('category', views.category, name='category'),
    path('allproducts/<slug:p>',views.allproducts,name="allproducts"),
    path('prodetail/<slug:p>', views.prodetail, name="prodetail"),
    path('regitr', views.regitr, name="regitr"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),

]

ecom/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_added=models.DateField(auto_now_add=True)
    active=models.BooleanField(default=True)

    def __str__(self):
     return self.products.name

    def subtotal(self):
        return self.quantity*self.products.price



class Account(models.Model):
    accountno=models.CharField(max_length=20)
    acctype=models.CharField(max_length=20)
    amount=models.CharField(max_length=20)

ecom/search/models.py
from django.db import models

# Create your models here.

ecom/shop/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='shop/category',null=True,blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=200,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='img/products',null=True,blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)


    def __str__(self):
       return self.name

ecom/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from cart.models import Cart
def add_cart(request,p):
    product=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(products=product,user=user)
        if cart.quantity<cart.products.stock:
            cart.quantity+=1
        cart.save()

    except Cart.DoesNotExist:
        cart=Cart.objects.create(user=user,products=product,quantity=1)
        cart.save()

    return redirect("cart:cartview")

def cartview(request):
    user=request.user
    try:
        cart=Cart.objects.filter(user=user)

    except Cart.DoesNotExist:
        pass
    return render(request,'cart.html',{'cart':cart})

ecom/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

def searchresult(request):
    query=""
    products=None
    if(request.method=="post"):
        query=request.POST.get('q')
        # print(query)
        if(query):
            products=Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request,'search.html',{'query':query,'products':products})

ecom/shop/views.py
from django.shortcuts import render,redirect
from shop.models import Product,Category
# from books import views
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib import messages
# from django.contrib.auth.decorators import login_required


def home(requset):
    c=Category.objects.all()

    return render(requset,'category.html',{'c':c})


def allproducts(requset,p):
    c=Category.objects.get(slug=p)
    product=Product.objects.filter(category__slug=p)
    return render(requset,'products.html',{'product':product,'c':c})

def prodetail(request,p):
    p=Product.objects.get(slug=p)
    return render(request,'detail.html',{'p':p})


def regitr(request):
    if(request.method=="POST"):
        u=request.POST["u"]
        p=request.POST["p"]
        cp=request.POST["cp"]
        e=request.POST["e"]
        f=request.POST["f"]
        l=request.POST["l"]
        if(cp==p):
            u=User.objects.create_user(username=u,
                                       password=p,
                                       email=e,
                                       first_name=f,
                                       last_name=l)
            u.save()
            return redirect('shop:home')
        else:
            messages.error(request, "PASSWORDS ARE NOT SAME")

    return render(request,'regitr.html')

def user_login(request):
    if(request.method=="POST"):
        username=request.POST['u']
        password=request.POST['p']
        user=authenticate(username=username,password=password)
        if user:
            login(request,user)
            return redirect('shop:home')
        else:
            messages.error(request,"invalid user credentials")

    return render(request,'login.html')

def user_logout(request):
    logout(request)
    return redirect('shop:home')

ecom/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet"  href="{% static 'css/custom.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

</head>
<body>
<div class="container-fluid">
  <header>
    <center> <img src="{% static 'img/m.png' %}" height="100px" width="100px" alt="img" > </center>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MY SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:home' %}">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:regitr' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>

            <li class="nav-item">
          <a class="nav-link" aria-current="page" href="">category</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.slug %}">{{i.name}}</a></li>
            {% endfor %}

          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-sharp fa-solid fa-cart-shopping fa-lg"></i></a>
        </li>

      </ul>
      <form method="POST" class="d-flex" action="{% url 'search:searchresult'%}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    </header>
</div>
{% block content %}
{% endblock %}

<!--<footer>-->
<!--<div style="background-color:grey;text-align:center;font-weight:bold;color:red;height:60px;width:100%;position:fixed;bottom:0;left:0;">    <p><i class="fa-regular fa-copyright"></i>Myshop pvt ltd.All right are reserved</p>-->
<!--  </div>-->
<!--</footer>-->

<center>
<h4>Welcome Home</h4>

{% if user.is_authenticated %}
<h4>{{user.username}}</h4>
{% else %}
<h4>Guest</h4>
{% endif %}
</center>
</body>

</html>

ecom/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="...">
  <h1>CART</h1>
  {{cart}}
</div>

{% endblock %}

ecom/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'img/bnr.jpg' %}" height="400px" width="100%">
</div>
<div class="container-fluid" style="margin-bottom:100px;">
    <h1 class="text-center">Our collections</h1>
    <p style="text-align:justify;">Calvin Klein is one of the world’s leading global fashion lifestyle brands with a history of bold, non-conformist ideals that inform everything we do. Founded in New York in 1968, the brand’s minimalist and sensual aesthetic drives our approach to product design and communication, creating a canvas that offers the possibility of limitless self-expression.</p>
</div>

<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
{% for i in c %}
<div class="col-sm-4" >
<div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." height="250px" width="100%">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.description}}</p>
    <a href="{% url 'shop:allproducts' i.slug %}" class=" btn btn-primary">product</a>
  </div>
</div>
</div>
{% endfor %}
</div>
</div>
{% endblock %}

ecom/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid" style="margin-bottom:100px;">
<div class="row">
<div class="col-sm-6 mt-5">
<img src="{{p.image.url}}" height="400px" width="400px">
</div>
    <div class="col-sm-6 mt-5">
    <h5 >{{p.name}}</h5>
    <h6 >{{p.price}}</h6>
    <h6>Product Description</h6>
    <p style="text-align:justify">{{p.description}}</p>

    <a href="{% url 'cart:cartview'  %}" class="btn btn-primary">ADD TO CART</a>
    </div>
</div>
</div>
{% endblock %}

ecom/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center> login </center>
<form method="post" >
  {% csrf_token %}
<div class="mb-3">
  <label class="form-label">USER NAME</label>
  <input type="text" class="form-control" name="u" placeholder="Enter user name">
</div>
<div class="mb-3">
  <label class="form-label">PASSWORD</label>
  <input type="password" class="form-control" name="p" placeholder="Enter password">
</div>
  <div class="mb-3">
    <input type="submit" class="btn btn-primary">
  </div>
</form>

{% if messages %}
{% for i in messages %}
<ul class= "messages">
<li>{{i}}</li>
</ul>
{% endfor %}
{% endif%}
{% endblock %}

ecom/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="mb-3">
  <label  class="form-label">address</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
</div>
<div class="mb-3">
  <label  class="form-label">phone</label>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
</div>
<div class="mb-3">
  <label  class="form-label">Accountno</label>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
</div>

ecom/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--{{product}}-->
<div>
<img src="{{c.image.url}}" height="400px" width="100%">
</div>
<div class="container-fluid" style="margin-bottom:100px;">
  <h1 class="text-center">{{c.name}}</h1>
  <p style="text-align:justify;">{{c.description}}</p>
</div>
<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
{% for i in product %}
<div class="col-sm-3" >
<div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." height="250px" width="100%">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <h6 class="card-title">{{i.price}}</h6>
    <p class="card-text">{{i.description}}</p>
    <a href="{% url 'shop:prodetail' i.slug %}" class=" btn btn-primary">details</a>
  </div>
</div>
</div>
{% endfor %}
</div>
</div>
{% endblock %}

ecom/templates/regitr.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center> register </center>
<form method="post" >
  {% csrf_token %}
<div class="mb-3">
  <label class="form-label">USER NAME</label>
  <input type="text" class="form-control" name="u" placeholder="Enter user name">
</div>
<div class="mb-3">
  <label class="form-label">PASSWORD</label>
  <input type="password" class="form-control" name="p" placeholder="Enter password">
</div><div class="mb-3">
  <label class="form-label">CONFIRM PASSWORD</label>
  <input type="password" class="form-control" name="cp" placeholder="Enter password again">
</div>

  <div class="mb-3">
  <label class="form-label">EMAIL</label>
  <input type="email" class="form-control" name="e" placeholder="Enter email">
</div><div class="mb-3">
  <label class="form-label">FIRST NAME</label>
  <input type="text" class="form-control" name="f" placeholder="Enter first name">
</div>
  <div class="mb-3">
  <label class="form-label">LAST NAME</label>
  <input type="text" class="form-control" name="l" placeholder="Enter last name">
</div>

   <div class="mb-3">
    <input type="submit" class="btn btn-primary">
  </div>
    </form>
{% if messages %}
{% for i in messages %}
<ul class= "messages">
<li>{{i}}</li>
</ul>
{% endfor %}
{% endif%}
{% endblock %}

ecom/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h5 class="text-center">You have searched for {{query}}</h5>
</div>

<div class="container-fluid" style="margin-bottom:100px;">
    <h6 class="text-center"> SEARCH RESULT </h6>
    <div class="row">

        {% for i in products %}
<div class="col-sm-4 mb-5" >
<div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." height="250px" width="100%">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>

    <a href="{% url 'shop:prodetail' i.slug %}" class=" btn btn-primary">details</a>
  </div>
</div>
</div>
 {% empty %}
        <h5 class="text-center text-danger">0 RESULTS FOUND</h5>
{% endfor %}
    </div>
</div>

{% endblock %}